(()=>{
const q=s=>document.querySelector(s),dialog=q('#nxFinder'),form=q('#nxFinderForm'),input=q('#nxFinderInput'),shoppingSubmit=form.onsubmit;let mode='shop';
q('#askNemu .nemu-speech').textContent='Nemu AI';q('#askNemu').setAttribute('aria-label','Buka Nemu AI');
q('#nxFinder header b').textContent='Nemu AI';q('#nxFinder header small').textContent='✦ Demo';
q('#nxFinder header').insertAdjacentHTML('beforeend','<button id="nxSearchHistory" aria-label="Riwayat pencarian">↶</button>');
let history=[];try{history=JSON.parse(localStorage.getItem('nemu.search-history')||'[]')}catch{}if(!Array.isArray(history))history=[];
function open(food){dialog.dataset.context=food?'food':'shop';q('.nx-finder-note').textContent='Demo pencarian katalog · AI belum terhubung';mode=food?'food':'shop';q('.nx-finder-welcome').hidden=false;q('#nxFinderResults').replaceChildren();input.value='';q('.nx-finder-welcome h2').textContent=food?'Mau makan apa hari ini?':'Hai, lagi cari apa?';q('.nx-finder-welcome p').innerHTML=food?'Ceritakan menu yang kamu inginkan.<br>Nemu bantu cari yang pas di kantong.':'Ceritakan kebutuhan dan budgetmu.<br>Nemu bantu temukan barang yang cocok.';q('.nx-finder-welcome > span').textContent='✦';input.placeholder=food?'Lagi ingin makan apa?':'Tanya Nemu…';input.setAttribute('aria-label',food?'Cari menu dengan Nemu AI':'Cari barang dengan Nemu AI');q('#nxFinderForm button').setAttribute('aria-label','Kirim pencarian');q('.nx-finder-chips').replaceChildren();(food?['Makan di bawah 30 ribu','Kopi di bawah 20 ribu','Burger keju']:['Jaket di bawah 200 ribu','HP di bawah 2 juta','Sepatu']).forEach(t=>{const b=document.createElement('button');b.textContent=t;q('.nx-finder-chips').append(b)});dialog.showModal()}
q('#askNemu').onclick=()=>{if(q('#sehat').classList.contains('active')){open(false);mode='health';dialog.dataset.context='health';q('.nx-finder-welcome h2').textContent='Mulai dari kebiasaan kecil';q('.nx-finder-welcome p').textContent='Aku bantu buka catatan makan dan pantau kebiasaan harianmu.';input.placeholder='Tanya Asisten Sehat…';input.setAttribute('aria-label','Pesan untuk Asisten Sehat');q('.nx-finder-chips').replaceChildren();['Catat makanan','Lihat diary','Catat air minum'].forEach(t=>{const b=document.createElement('button');b.textContent=t;q('.nx-finder-chips').append(b)});q('.nx-finder-note').textContent='Asisten demo · bukan saran medis';return}open(q('#makan').classList.contains('active')||q('#restoPage').classList.contains('active'))};
q('#foodSearch').closest('label').insertAdjacentHTML('afterend','<button class="nx-food-ai" id="nxFoodAI"><span class="nx-food-ai-icon">✦</span><span><b>Bingung mau makan apa?</b><small>Cari menu sesuai selera & budget dengan Nemu AI</small></span><strong>↗</strong></button>');q('#nxFoodAI').onclick=()=>open(true);
form.onsubmit=e=>{const raw=input.value.trim();if(!raw){e.preventDefault();return}history=[{query:raw,mode},...history.filter(h=>h.query!==raw)].slice(0,8);try{localStorage.setItem('nemu.search-history',JSON.stringify(history))}catch{}if(mode==='health'){e.preventDefault();const out=q('#nxFinderResults');out.replaceChildren();const p=document.createElement('p');p.textContent='Pilih langkah yang ingin kamu lakukan. Catatanmu tersimpan di Nemu Sehat.';out.append(p);[['manual','Catat makanan'],['diary','Lihat diary'],['water','Catat air minum']].forEach(([action,label])=>{const b=document.createElement('button');b.className='nx-find-product';b.textContent=label;b.onclick=()=>{dialog.close();document.dispatchEvent(new CustomEvent('nemu-health-action',{detail:action}))};out.append(b)});return}if(mode==='shop'){shoppingSubmit(e);return}e.preventDefault();const text=raw.toLowerCase(),budget=text.match(/(\d+(?:[.,]\d+)?)\s*(ribu|rb|k)/),limit=budget?Number(budget[1].replace(',','.'))*1000:Infinity;const words=text.replace(/di bawah|dibawah|makanan|makan|budget|cari|aku|mau|yang|untuk|ribu|rb|\d+/g,' ').split(/\s+/).filter(w=>w.length>2);if(words.includes('nasi'))words.push('rice');if(words.includes('kopi'))words.push('cappuccino');const found=demoMenus.flatMap((menus,r)=>menus.map(m=>({...m,r}))).filter(m=>m.price<=limit&&(!words.length||words.some(w=>(m.name+' '+foods[m.r].name).toLowerCase().includes(w))));const out=q('#nxFinderResults');out.replaceChildren();q('.nx-finder-welcome').hidden=true;const heading=document.createElement('h3');heading.textContent=found.length?found.length+' menu yang bisa kamu coba':'Belum ada menu yang cocok';out.append(heading);found.forEach(m=>{const b=document.createElement('button');b.className='nx-find-product';const img=document.createElement('img');img.src='assets/'+m.image;img.alt='';const copy=document.createElement('span'),name=document.createElement('b'),detail=document.createElement('small');name.textContent=m.name+' · '+rupiah(m.price);detail.textContent=foods[m.r].name+' · '+foods[m.r].distance+' · Lihat menu ↗';copy.append(name,detail);b.append(img,copy);b.onclick=()=>{dialog.close();openResto(m.r)};out.append(b)});if(!found.length){const p=document.createElement('p');p.textContent='Coba “kopi”, “burger”, atau budget lain.';out.append(p)}};
q('#nxSearchHistory').innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11a9 9 0 1 1 2.6 7.4M3 4v7h7M12 7v5l3 2"/></svg>';q('#nxSearchHistory').onclick=()=>{q('.nx-finder-welcome').hidden=true;const out=q('#nxFinderResults');out.replaceChildren();const h=document.createElement('h3');h.textContent='Pencarian terakhir';out.append(h);if(!history.length){const p=document.createElement('p');p.textContent='Pencarianmu akan muncul di sini.';out.append(p)}history.forEach(item=>{const b=document.createElement('button');b.className='nx-find-product';b.textContent=(item.mode==='food'?'Makan · ':'Belanja · ')+item.query;b.onclick=()=>{open(item.mode==='food');input.value=item.query;form.requestSubmit()};out.append(b)})};
})();
