(()=>{
const q=s=>document.querySelector(s);
// Give the catalogue priority; keep rewards as a compact secondary entry.
const promo=q('#promoCarousel'),campaign=q('#belanja > .nx-campaign'),intro=q('#belanja > .nx-discovery');
if(campaign)promo.after(campaign);
if(intro){q('#profilePage').append(intro);intro.querySelector('b').textContent='Atur Nemu sesuai kebutuhanmu';intro.querySelector('p').textContent='Ubah pilihan dan kenalan lagi dengan Nemu.';intro.querySelector('button').textContent='Atur ↗'}
q('#nxBuddy').onclick=()=>{document.querySelector('[data-view=chat]').click();openChat('Rio · Asisten Nemu')};
q('#nxBuddy').setAttribute('aria-label','Buka Nemu Teman');
q('#askNemu').innerHTML='<span class="nemu-speech">Tanya Nemu</span><span class="nx-search-spark" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9.5" cy="10.5" r="5.5"/><path d="m5.5 14.5-3 3M18 2l1.1 3.4L22.5 6.5l-3.4 1.1L18 11l-1.1-3.4-3.4-1.1 3.4-1.1Z"/></svg></span>';
q('#askNemu').setAttribute('aria-label','Tanya Nemu, cari barang dengan AI');
document.body.insertAdjacentHTML('beforeend',`<dialog id="nxFinder" class="nx-finder"><header><button id="nxFinderClose" aria-label="Tutup pencarian"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><b>✦ Nemu Cari</b><small>Preview AI</small></header><div class="nx-finder-body"><div class="nx-finder-welcome"><span>⌕ ✦</span><h2>Lagi mencari apa?</h2><p>Ceritakan barang dan budgetmu.<br>Aku bantu temukan pilihan dari katalog Nemu.</p></div><div id="nxFinderResults" aria-live="polite"></div></div><div class="nx-finder-chips"><button>Jaket di bawah 200 ribu</button><button>HP di bawah 2 juta</button><button>Sepatu</button></div><form id="nxFinderForm"><textarea id="nxFinderInput" rows="1" placeholder="Ceritakan yang kamu cari…" aria-label="Barang yang dicari" required></textarea><button aria-label="Cari barang">↑</button></form><p class="nx-finder-note">Demo pencarian katalog · AI belum terhubung</p></dialog>`);
const finder=q('#nxFinder');q('#askNemu').onclick=()=>{finder.showModal();q('#nxFinderInput').focus()};q('#nxFinderClose').onclick=()=>finder.close();
q('#nxFinderForm').onsubmit=e=>{e.preventDefault();const query=q('#nxFinderInput').value.toLowerCase(),budget=query.match(/(\d+(?:[.,]\d+)?)\s*(juta|ribu|rb|jt)/),limit=budget?Number(budget[1].replace(',','.'))*(/juta|jt/.test(budget[2])?1000000:1000):Infinity;const words=query.replace(/di bawah|dibawah|budget|cari|aku|mau|yang|untuk|ribu|juta|\d+/g,' ').split(/\s+/).filter(w=>w.length>2);if(/hp/.test(query))words.push('ponsel');if(/sepatu/.test(query))words.push('sneakers');const found=products.map((p,i)=>({p,i})).filter(({p})=>p.price<=limit&&(!words.length||words.some(w=>(p.name+' '+p.category+' '+(p.keywords||'')).toLowerCase().includes(w))));const out=q('#nxFinderResults');out.replaceChildren();const title=document.createElement('h3');title.textContent=found.length?found.length+' pilihan buat kamu':'Belum ketemu yang cocok';out.append(title);found.slice(0,8).forEach(({p,i})=>{const b=document.createElement('button');b.className='nx-find-product';const img=document.createElement('img');img.src=productImage(p.image);img.alt='';const text=document.createElement('span');text.textContent=p.name+' · '+rupiah(p.price);b.append(img,text);b.onclick=()=>{finder.close();openProduct(i)};out.append(b)});if(!found.length){const p=document.createElement('p');p.textContent='Coba nama barang lain atau naikkan budgetmu.';out.append(p)}q('.nx-finder-welcome').hidden=true};
q('.nx-finder-chips').onclick=e=>{if(e.target.tagName==='BUTTON'){q('#nxFinderInput').value=e.target.textContent;q('#nxFinderForm').requestSubmit()}};
q('#roomWelcome h2').innerHTML='Hai, aku Nemu';q('#roomWelcome p').innerHTML='Teman untuk cari ide makan,<br>merencanakan hari, dan ngobrol sebentar.';
})();
