(()=>{
const $=s=>document.querySelector(s),profile=$('#profilePage');profile.classList.add('nx');$('#profilePage .profile-note').remove();$('#profilePage .profile-card p').textContent='Semua aktivitas dan pilihanmu, di sini.';
profile.insertAdjacentHTML('beforeend',`<button class="nx-referral-banner" id="nxReferral"><span>♧</span><div><small>LEBIH SERU BARENG TEMAN</small><h2>Ajak teman, nemu bareng.</h2><p>Lihat kode undanganmu ↗</p></div><img src="assets/promo-star-mascot.png" alt="Nemu membawa hadiah"></button><h2 class="nx-account-label">Aktivitasmu</h2><div class="nx-account-group"><button data-account="cart"><span>♧</span> Keranjang belanja <i>›</i></button><button data-account="health"><span>◒</span> Diary & progres sehat <i>›</i></button><button data-account="missions"><span>✦</span> Misi harian & reward <i>›</i></button></div><h2 class="nx-account-label">Preferensi</h2><div class="nx-account-group"><button data-account="personal"><span>◎</span> Nama & tujuan awal <i>›</i></button><button data-account="referral"><span>♡</span> Kode referral <i>›</i></button></div><h2 class="nx-account-label">Kenalan lebih dekat</h2><div class="nx-account-group"><a href="https://nemu-ai.com" target="_blank" rel="noopener"><span>↗</span> Jelajahi Nemu <i>↗</i></a><a href="https://seller.nemu-ai.com/register" target="_blank" rel="noopener"><span>◇</span> Program affiliate & seller <i>↗</i></a><button data-account="new"><span>✧</span> Yang baru di Nemu <i>›</i></button></div><h2 class="nx-account-label">Bantuan</h2><div class="nx-account-group"><button data-account="help"><span>?</span> Panduan penggunaan <i>›</i></button><button data-account="feedback"><span>✎</span> Usulkan fitur <i>›</i></button><button data-account="privacy"><span>▣</span> Data & privasi prototipe <i>›</i></button></div><p class="nx-muted" style="text-align:center;margin:25px 0">Nemu Apps · desain prototipe<br>Teman untuk kebutuhan sehari-hari.</p>`);
$('#profilePage .profile-links').hidden=true;const challenge=profile.querySelector('.nx-campaign');if(challenge)$('#nxReferral').after(challenge);
const dialog=$('#nxDialog'),body=$('#nxDialogBody');function show(html){dialog.classList.remove('nx-intro');body.innerHTML=html;if(!dialog.open)dialog.showModal()}
let referral={code:'NEMU-'+Math.random().toString(36).slice(2,8).toUpperCase(),used:null};try{referral={...referral,...JSON.parse(localStorage.getItem('nemu.referral.v1')||'{}')}}catch{}const save=()=>{try{localStorage.setItem('nemu.referral.v1',JSON.stringify(referral))}catch{}};save();
function refer(){show(`<span class="nx-overline">AJAK TEMAN · DEMO</span><h2>Yang seru,<br>dibagi bareng.</h2><img class="nx-intro-img" src="assets/promo-star-mascot.png" alt="Nemu"><p class="nx-muted">Bagikan kode ini kepada temanmu untuk mencoba alur undangan Nemu.</p><div class="nx-voucher"><small>KODE UNDANGANMU</small><code>${referral.code}</code><button class="nx-btn" id="nxCopyReferral">Salin kode</button></div><div id="nxReferralStatus" role="status" class="nx-muted"></div>${referral.used?'<p class="nx-muted">Kode teman sudah tersimpan untuk demo ini.</p>':'<form id="nxReferralForm" class="nx-form"><label>Punya kode dari teman?<input name="code" placeholder="NEMU-XXXXXX" pattern="[Nn][Ee][Mm][Uu]-[A-Za-z0-9]{6}" required maxlength="11"></label><button class="nx-btn">Simpan kode teman</button></form>'}<p class="nx-muted">Belum memverifikasi undangan nyata atau memberikan reward. Kode dan status tersimpan hanya di browser ini.</p>`);$('#nxCopyReferral').onclick=async()=>{try{await navigator.clipboard.writeText(referral.code);$('#nxReferralStatus').textContent='Kode berhasil disalin.'}catch{$('#nxReferralStatus').textContent='Salin kode yang ditampilkan di atas secara manual.'}};$('#nxReferralForm')?.addEventListener('submit',e=>{e.preventDefault();const code=new FormData(e.target).get('code').trim().toUpperCase();if(code===referral.code){$('#nxReferralStatus').textContent='Gunakan kode milik teman, bukan kodemu sendiri.';return}referral.used=code;save();refer()})}
$('#nxReferral').onclick=refer;profile.addEventListener('click',e=>{const b=e.target.closest('[data-account]');if(!b)return;const action=b.dataset.account;if(action==='referral')refer();if(action==='cart')openShoppingCart();if(action==='missions')openMissions();if(action==='health')$('#nxProfileHealth').click();if(action==='personal')$('#nxProfileSetup').click();if(action==='new')show('<span class="nx-overline">YANG BARU</span><h2>Nemu, makin dekat.</h2><p class="nx-muted">• Diary makanan per tanggal dan catatan air.<br>• Progres tujuh hari dari catatanmu.<br>• Tantangan 7 Hari Bareng Nemu.<br>• Referral dan akun yang lebih rapi.<br>• Keranjang barang tersimpan di perangkat.</p>');if(action==='help')show('<h2>Mulai dari kebutuhanmu.</h2><details open><summary>Belanja & keranjang</summary><p class="nx-muted">Buka detail barang, tekan Tambah ke keranjang. Jumlah bisa diubah dari ikon keranjang.</p></details><details><summary>Catatan makanan</summary><p class="nx-muted">Buka Sehat → Diary. Pilih tanggal dan waktu makan, lalu masukkan nama serta energi dari catatanmu.</p></details><details><summary>Misi & voucher</summary><p class="nx-muted">Buka kartu 7 Hari Bareng Nemu. Selesaikan empat misi sebelum waktunya habis untuk mencoba klaim voucher demo.</p></details>');if(action==='privacy')show('<h2>Catatanmu di perangkatmu.</h2><p class="nx-muted">Prototipe ini menyimpan preferensi, diary, keranjang, misi, dan kode referral di localStorage browser. Foto makanan hanya ditampilkan sementara dan tidak diunggah. Tidak ada login, analisis AI, atau pembayaran yang terhubung. Menghapus data situs dari browser akan menghapus catatan lokal.</p>');if(action==='feedback'){show('<h2>Ada ide buat Nemu?</h2><form id="nxFeedback" class="nx-form"><label>Ide atau masukanmu<input name="idea" required maxlength="500" placeholder="Aku ingin Nemu bisa..."></label><p class="nx-muted">Masukan disimpan sebagai draf lokal, belum dikirim ke tim Nemu.</p><button class="nx-btn">Simpan draf</button></form>');$('#nxFeedback').onsubmit=e=>{e.preventDefault();try{localStorage.setItem('nemu.feedback.draft',new FormData(e.target).get('idea'));show('<h2>Draf tersimpan.</h2><p class="nx-muted">Terima kasih sudah ikut membentuk Nemu. Draf ini hanya ada di browsermu.</p>')}catch{show('<p>Penyimpanan tidak tersedia. Salin masukanmu agar tidak hilang.</p>')}}}});

// Account information architecture adapted to Nemu's marketplace and daily tools.
const oldGroups=[...profile.querySelectorAll('.nx-account-label,.nx-account-group')];oldGroups.forEach(x=>x.remove());
const footer=profile.querySelector('p.nx-muted:last-child');if(footer)footer.remove();
profile.querySelector('.profile-card').insertAdjacentHTML('beforebegin','<div class="nx-account-heading"><h1>Akun</h1><span>Ruang pribadimu</span></div>');
profile.querySelector('.profile-card').insertAdjacentHTML('beforeend','<button class="nx-mini" data-account="details" aria-label="Edit profil">✎</button>');
const groups=[['Belanja & aktivitas',[['cart','bag','Keranjang belanja'],['orders','clock','Riwayat pesanan'],['missions','spark','Misi harian & reward'],['referral','heart','Ajak teman']]],['Personalisasi',[['details','user','Detail profil'],['healthSettings','leaf','Tujuan & target Sehat'],['health','food','Diary makanan'],['weightHistory','tag','Catatan berat badan'],['assistant','chat','Asisten pribadi Nemu'],['appSettings','edit','Pengaturan aplikasi']]],['Berkembang bersama Nemu',[['seller','house','Mulai jadi seller / affiliate'],['new','spark','Yang baru di Nemu'],['referral','heart','Rekomendasikan ke teman']]],['Bantuan & informasi',[['help','chat','Panduan penggunaan'],['feedback','edit','Usulkan fitur'],['termsDemo','tag','Tentang penggunaan prototipe'],['privacy','user','Data & privasi'],['preferences','edit','Preferensi komunikasi']]]];
profile.insertAdjacentHTML('beforeend',groups.map(([title,rows])=>`<h2 class="nx-account-label">${title}</h2><div class="nx-account-group">${rows.map(([id,icon,label])=>`<button data-account="${id}"><span><svg><use href="assets/sprite.svg#${icon==='clock'?'back':icon}"/></svg></span>${label}<i>›</i></button>`).join('')}</div>`).join('')+'<div class="nx-account-footer"><b>nemu<span>.ai</span></b><p>Teman untuk kebutuhan sehari-hari.</p><small>Versi desain 0.2 · akun lokal demo</small></div>');
function readProfile(){try{return JSON.parse(localStorage.getItem('nemu.experience.v2'))||{name:'Ferry'}}catch{return {name:'Ferry'}}}
function identity(){const info=readProfile(),name=info.name||'Ferry';profile.querySelector('.profile-card h1').textContent=name;profile.querySelector('.profile-initial').textContent=name.slice(0,1).toUpperCase();profile.querySelector('.profile-card p').textContent=(info.city||'Lengkapi profilmu')+' · akun demo';const avatar=document.querySelector('.topbar .avatar-small');avatar.textContent=name.slice(0,1).toUpperCase();avatar.setAttribute('aria-label','Profil '+name)}identity();document.addEventListener('nemu-health-saved',identity);
profile.addEventListener('click',e=>{const b=e.target.closest('[data-account]');if(!b)return;const action=b.dataset.account;
if(action==='details'){const info=readProfile();show(`<span class="nx-overline">DETAIL PROFIL</span><h2>Biar makin kenal.</h2><form id="nxEditProfile" class="nx-form"><label>Nama panggilan<input name="name" required maxlength="30"></label><label>Kota (opsional)<input name="city" maxlength="50" placeholder="Contoh: Tangerang"></label><p class="nx-muted">Tersimpan di browser ini. Tidak dibagikan ke seller.</p><button class="nx-btn">Simpan profil</button></form>`);$('#nxEditProfile [name="name"]').value=info.name||'Ferry';$('#nxEditProfile [name="city"]').value=info.city||'';$('#nxEditProfile').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),name=String(form.get('name')).trim();if(!name)return;const update={...readProfile(),name,city:String(form.get('city')).trim()};localStorage.setItem('nemu.experience.v2',JSON.stringify(update));document.dispatchEvent(new CustomEvent('nemu-profile-updated',{detail:update}));identity();dialog.close()}}
if(action==='orders')show('<span class="nx-overline">RIWAYAT PESANAN</span><h2>Belum ada pesanan.</h2><div class="nx-empty"><img class="nx-intro-img" src="assets/promo-tote-mascot.png" alt="Nemu"><p>Barang di keranjang belum menjadi pesanan. Checkout dan pembayaran belum terhubung di prototipe ini.</p></div><button class="nx-btn" id="nxOrdersShop">Jelajahi Belanja</button>');
if(action==='orders')$('#nxOrdersShop').onclick=()=>{dialog.close();document.querySelector('[data-view="belanja"]').click()};
if(action==='assistant')$('#askNemu').click();
if(action==='seller')window.open('https://seller.nemu-ai.com/register','_blank','noopener');
if(action==='healthSettings'||action==='weightHistory'){document.querySelector('[data-view="sehat"]').click();document.dispatchEvent(new CustomEvent('nemu-health-action',{detail:action==='healthSettings'?'settings':'insight'}))}
if(action==='termsDemo')show('<span class="nx-overline">TENTANG PROTOTIPE</span><h2>Kenali Nemu yang sedang kamu coba.</h2><p class="nx-muted">Ini adalah prototipe untuk mengeksplorasi desain dan alur aplikasi. Produk, resto, live, voucher, dan referral menggunakan data demo. Belum ada pembayaran, langganan, atau pemesanan nyata.</p><p class="nx-muted">Informasi ini bukan syarat layanan final. Dokumen resmi akan mengikuti layanan Nemu saat terintegrasi.</p>');
if(action==='appSettings'){let prefs={reduced:false};try{prefs={...prefs,...JSON.parse(localStorage.getItem('nemu.app-settings')||'{}')}}catch{}show(`<span class="nx-overline">PENGATURAN APLIKASI</span><h2>Buat senyamanmu.</h2><div class="nx-setting-row"><span><b>Kurangi gerakan</b><small>Hentikan animasi sapaan Nemu.</small></span><input id="nxReduceMotion" type="checkbox" aria-label="Kurangi gerakan" ${prefs.reduced?'checked':''}></div><div class="nx-setting-row"><span><b>Bahasa</b><small>Bahasa Indonesia</small></span><small>Aktif</small></div><p class="nx-muted">Preferensi berlaku di browser ini.</p>`);$('#nxReduceMotion').onchange=e=>{prefs.reduced=e.target.checked;localStorage.setItem('nemu.app-settings',JSON.stringify(prefs));document.body.classList.toggle('nx-reduce-motion',prefs.reduced)}}
if(action==='preferences'){let enabled=false;try{enabled=localStorage.getItem('nemu.promo-preference')==='true'}catch{}show(`<span class="nx-overline">PREFERENSI KOMUNIKASI</span><h2>Pilih kabar yang kamu mau.</h2><div class="nx-setting-row"><span><b>Kabar promo Nemu</b><small>Preferensi simulasi, tidak mengirim notifikasi.</small></span><input id="nxPromoPreference" type="checkbox" aria-label="Kabar promo Nemu" ${enabled?'checked':''}></div><p class="nx-muted">Belum tersambung ke email atau notifikasi perangkat. Kamu bisa mengubah pilihan ini kapan saja.</p>`);$('#nxPromoPreference').onchange=e=>localStorage.setItem('nemu.promo-preference',String(e.target.checked))}
});
try{document.body.classList.toggle('nx-reduce-motion',JSON.parse(localStorage.getItem('nemu.app-settings')||'{}').reduced===true)}catch{}
})();
